name: Run Binance Balance Script

on:
  schedule:
    - cron: '0 0 * * *' # This cron expression schedules the job to run every day at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3' # Ensure it matches your local Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }} # This assumes 'sheet' is stored as a secret named 'SHEET_ID'
        BINANCE_API_KEY: ${{ secrets.API_KEY }}
        BINANCE_SECRET_KEY: ${{ secrets.SECRET_API_KEY }}
        CREDENTIALS: ${{secrets.CREDENTIALS}}
        TOKEN: ${{secrets.TOKEN}}
        # Add any other secrets or environment variables your script requires
      run: python spreadsheet.py
